INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('2','2','2','2','2','2','2','2','2','2','2','2','2','2','2','2','2','2','2');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('3','3','3','3','3','3','3','3','3','3','3','3','3','3','3','3','3','3','3');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('4','4','4','4','4','4','4','4','4','4','4','4','4','4','4','4','4','4','4');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('5','5','5','5','5','5','5','5','5','5','5','5','5','5','5','5','5','5','5');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('6','6','6','6','6','6','6','6','6','6','6','6','6','6','6','6','6','6','6');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('7','7','7','7','7','7','7','7','7','7','7','7','7','7','7','7','7','7','7');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('8','8','8','8','8','8','8','8','8','8','8','8','8','8','8','8','8','8','8');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('9','9','9','9','9','9','9','9','9','9','9','9','9','9','9','9','9','9','9');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('10','10','10','10','10','10','10','10','10','10','10','10','10','10','10','10','10','10','10');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('11','11','11','11','11','11','11','11','11','11','11','11','11','11','11','11','11','11','11');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('12','12','12','12','12','12','12','12','12','12','12','12','12','12','12','12','12','12','12');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('13','13','13','13','13','13','13','13','13','13','13','13','13','13','13','13','13','13','13');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('14','14','14','14','14','14','14','14','14','14','14','14','14','14','14','14','14','14','14');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('15','15','15','15','15','15','15','15','15','15','15','15','15','15','15','15','15','15','15');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('16','16','16','16','16','16','16','16','16','16','16','16','16','16','16','16','16','16','16');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('17','17','17','17','17','17','17','17','17','17','17','17','17','17','17','17','17','17','17');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('18','18','18','18','18','18','18','18','18','18','18','18','18','18','18','18','18','18','18');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('19','19','19','19','19','19','19','19','19','19','19','19','19','19','19','19','19','19','19');
INSERT INTO STUDENT (ID, ADDRESS, CITY, COUNTRY, DATE_OFBIRTH, DEPARTMENT, EDUCATION_STATUS, EDUCATION_YEAR, FACULTY, GENDER, ID_NUMBER, NAME
, NATIONALITY, OCCUPATION, PHONE_NUMBER, PASSPORT_NUMBER, PLACE_OF_BIRTH, SURNAME, UNIVERSITY) VALUES
('20','20','20','20','20','20','20','20','20','20','20','20','20','20','20','20','20','20','20');